### ISSUE TITLE
"npm run examples" throws "TypeError: _prismejsMin2.default is not a constructor"

### ISSUE THREAD

**Issue by Alexandre-Nourissier** [tom4dev/prismejs#1]
Hello, I tried running the examples projects as instructed in the readme.md and encounter the following error: 

PS C:\dev\github.com\tom4dev\prismejs> npm run examples

> prismejs@1.0.5 examples C:\dev\github.com\tom4dev\prismejs
> babel-node ./examples/demo.js

C:\dev\github.com\tom4dev\prismejs\examples\demo.js:17
var PrismeJS = new _prismejsMin2.default();
               ^

TypeError: _prismejsMin2.default is not a constructor
    at Object.<anonymous> (C:/dev/github.com/tom4dev/prismejs/examples/demo.js:5:18)
    at Module._compile (module.js:570:32)
    at loader (C:\dev\github.com\tom4dev\prismejs\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\dev\github.com\tom4dev\prismejs\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at Object.<anonymous> (C:\dev\github.com\tom4dev\prismejs\node_modules\babel-cli\lib\_babel-node.js:154:22)
    at Module._compile (module.js:570:32)

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "examples"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! prismejs@1.0.5 examples: `babel-node ./examples/demo.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prismejs@1.0.5 examples script 'babel-node ./examples/demo.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the prismejs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./examples/demo.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs prismejs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls prismejs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\github.com\tom4dev\prismejs\npm-debug.log

**Comment by thomasbrodusch** [comment]
@Alexandre-Nourissier is fixed in  https://github.com/tom4dev/prismejs/commit/104371ba6cfc80d462d825541e89352be6ade9aa ! 

Thanks for your comment 🙏
